#!/bin/bash

# Check if the script is run with root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script as root."
    exit 1
fi

username="shell02"
password="shell02"

# Check if the user already exists
if id "$username" &>/dev/null; then
    echo "User '$username' already exists."
    exit 1
fi

# Create the user with the hardcoded username and password
useradd -m -s /bin/bash "$username"
echo "$username:$password" | chpasswd

echo "User '$username' created successfully with password."

# Create a directory named inhere
mkdir inhere
echo "Directory named 'inhere' has been created."
chown 441 inhere
chgrp shell03 inhere

# Create a file named .hidden in the directory inhere
echo "The password to the next level is shell03" > inhere/.hidden
echo "File named '.hidden' has been created in 'inhere' directory."
chown 440 inhere/.hidden
chgrp shell03 inhere/.hidden
